import React from "react";
import { NavigationContainer } from "@react-navigation/native";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { SupportChat } from "@src/utility/supportChat";

import {
  navigationRef,
  onReady,
  onStateChange,
  onLastScreenLeave,
} from "@src/navigation";

const Stack = createNativeStackNavigator();

const listeners = ({ navigation, route }) => ({
  beforeRemove: (e) => {
    if (e.data.action.type === "GO_BACK") {
      onLastScreenLeave(e);
    }
  },
});

const screenOptions = {
  // animation: 'none',
  // orientation: 'portrait'
};

const NavRoot = ({ navigation }) => {
  return null;
};

const Navigator = () => {
  return (
    <NavigationContainer
      ref={navigationRef}
      onReady={onReady}
      onStateChange={onStateChange}
    >
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
          contentStyle: { backgroundColor: '#FFFFFF' },
        }}
        initialRouteName="NavRoot"
        screenListeners={listeners}
      >
        <Stack.Screen
          options={screenOptions}
          name="NavRoot"
          component={NavRoot}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicHome"
          component={require("@src/screen/Public/Home").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicLanguage"
          component={require("@src/screen/Public/Language").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicBrand"
          component={require("@src/screen/Public/Brand").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicHelpCentre"
          component={require("@src/screen/Public/HelpCentre").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicSearch"
          component={require("@src/screen/Public/Search").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicStore"
          component={require("@src/screen/Public/Store").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicPageView"
          component={require("@src/screen/Public/PageView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicReferralInvite"
          component={require("@src/screen/Public/ReferralInvite").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicWalkThroughList"
          component={require("@src/screen/Public/WalkThroughList").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="PlayHome"
          component={require("@src/screen/Play/Home").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayChannelList"
          component={require("@src/screen/Play/ChannelList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayChannelView"
          component={require("@src/screen/Play/ChannelView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayMovieList"
          component={require("@src/screen/Play/MovieList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayLiveTvList"
          component={require("@src/screen/Play/LiveTvList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayLiveTvView"
          component={require("@src/screen/Play/LiveTvView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayMusicList"
          component={require("@src/screen/Play/MusicList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayMusicView"
          component={require("@src/screen/Play/MusicView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayGameList"
          component={require("@src/screen/Play/GameList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayGameView"
          component={require("@src/screen/Play/GameView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayMovieView"
          component={require("@src/screen/Play/MovieView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayNewsList"
          component={require("@src/screen/Play/NewsList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PlayNewsView"
          component={require("@src/screen/Play/NewsView").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="PublicOffers"
          component={require("@src/screen/Public/Offers").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicOfferView"
          component={require("@src/screen/Public/OfferView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicCoupon"
          component={require("@src/screen/Public/Coupon").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="PublicCouponView"
          component={require("@src/screen/Public/CouponView").default}
        />
        {/* <Stack.Screen options={screenOptions} name='PublicPlans' component={require('@src/screen/Public/Plans').default} /> */}
        <Stack.Screen
          options={screenOptions}
          name="PublicPlanView"
          component={require("@src/screen/Public/PlanView").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="PublicPlans"
          component={require("@src/screen/Shop/BundleList").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="ShopHome"
          component={require("@src/screen/Shop/Home").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopList"
          component={require("@src/screen/Shop/List").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopGameList"
          component={require("@src/screen/Shop/GameList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopChannelList"
          component={require("@src/screen/Shop/ChannelList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopView"
          component={require("@src/screen/Shop/View").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopCart"
          component={require("@src/screen/Shop/Cart").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopBundleList"
          component={require("@src/screen/Shop/BundleList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ShopMobileList"
          component={require("@src/screen/Shop/MobileList").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserLogin"
          component={require("@src/screen/User/Login").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserLoginTerms"
          component={require("@src/screen/User/LoginTerms").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserMobileVerification"
          component={require("@src/screen/User/MobileVerification").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserLoginPinCreate"
          component={require("@src/screen/User/LoginPinCreate").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserLoginPinCheck"
          component={require("@src/screen/User/LoginPinCheck").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserLoginProfile"
          component={require("@src/screen/User/LoginProfile").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserLogout"
          component={require("@src/screen/User/Logout").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserHome"
          component={require("@src/screen/User/Home").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserPlanUsage"
          component={require("@src/screen/User/PlanUsage").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserProfile"
          component={require("@src/screen/User/Profile").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserProfileEdit"
          component={require("@src/screen/User/ProfileEdit").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserSubmitNIN"
          component={require("@src/screen/User/SubmitNIN").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserAddNumber"
          component={require("@src/screen/User/AddNumber").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserTransactionList"
          component={require("@src/screen/User/TransactionList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserConfiguration"
          component={require("@src/screen/User/Configuration").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserTroubleshooting"
          component={require("@src/screen/User/Troubleshooting").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserSubscription"
          component={require("@src/screen/User/Subscription").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserBundleList"
          component={require("@src/screen/User/BundleList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserBundleCart"
          component={require("@src/screen/User/BundleCart").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserTariffPlan"
          component={require("@src/screen/User/TariffPlan").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserPostpaidList"
          component={require("@src/screen/User/PostpaidList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserRechargeHome"
          component={require("@src/screen/User/RechargeHome").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserRechargePlanList"
          component={require("@src/screen/User/RechargePlanList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserTopup"
          component={require("@src/screen/User/Topup").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserShare"
          component={require("@src/screen/User/Share").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserBorrow"
          component={require("@src/screen/User/Borrow").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserCallertuneList"
          component={require("@src/screen/User/CallertuneList").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserCallertune"
          component={require("@src/screen/User/Callertune").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserBillPayment"
          component={require("@src/screen/User/BillPayment").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserPayment"
          component={require("@src/screen/User/Payment").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserBankAccount"
          component={require("@src/screen/User/BankAccount").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserAddBankAccount"
          component={require("@src/screen/User/AddBankAccount").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="UserAddress"
          component={require("@src/screen/User/Address").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="BundleBorrowData"
          component={require("@src/screen/Bundle/BorrowData").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="UserMyRewards"
          component={require("@src/screen/User/MyRewards").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinHome"
          component={require("@src/screen/GoldenCoin/Home").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinSpinTheWheel"
          component={require("@src/screen/GoldenCoin/SpinTheWheel").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinProfile"
          component={require("@src/screen/GoldenCoin/Profile").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinBadges"
          component={require("@src/screen/GoldenCoin/Badges").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinLeaderBoard"
          component={require("@src/screen/GoldenCoin/Leaderboard").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinQuizChallenge"
          component={require("@src/screen/GoldenCoin/QuizChallenge").default}
        />

        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinParticipate"
          component={require("@src/screen/GoldenCoin/Participate").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinActiveOffers"
          component={require("@src/screen/GoldenCoin/ActiveOffers").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinOnlineShopping"
          component={require("@src/screen/GoldenCoin/OnlineShopping").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinSubscriptions"
          component={require("@src/screen/GoldenCoin/Subscriptions").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinCashback"
          component={require("@src/screen/GoldenCoin/Cashback").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinMomo"
          component={require("@src/screen/GoldenCoin/Momo").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinEGifts"
          component={require("@src/screen/GoldenCoin/EGifts").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinRechargeBills"
          component={require("@src/screen/GoldenCoin/RechargeBills").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinPostpaid"
          component={require("@src/screen/GoldenCoin/Postpaid").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinRewards"
          component={require("@src/screen/GoldenCoin/Rewards").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinOfferView"
          component={require("@src/screen/GoldenCoin/OfferView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinRewardView"
          component={require("@src/screen/GoldenCoin/RewardView").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="GoldenCoinUserLevel"
          component={require("@src/screen/GoldenCoin/UserLevel").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="ChangeSpendLimit"
          component={require("@src/screen/User/ChangeSpendLimit").default}
        />
        <Stack.Screen
          options={screenOptions}
          name="CreditLimit"
          component={require("@src/screen/User/CreditLimit").default}
        />
      </Stack.Navigator>
      <SupportChat />
    </NavigationContainer>
  );
};

export default Navigator;
